#pragma config(Sensor, in1,    magSens1,       sensorAnalog)
#pragma config(Sensor, in2,    magSens2,       sensorAnalog)
#pragma config(Motor,  port7,           flagServoLeft, tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           flagServoRight, tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "smvex.h"

#define CLAW_POWER 127
#define READ_THRESH 2000

// #define TEST

void init(Controller *c) {
    c->Left->y_scale = -1;
    c->Left->x_scale = -1;
}

void loop(Controller *c) {
    drive_control_from(c->Left, port2, port3);

    map_threshold(c->Right, Y_AXIS, 32, port4);

    if (c->btn6.up) {
        motor[port5] = CLAW_POWER;
    } else if (c->btn5.up) {
        motor[port5] = -CLAW_POWER;
    } else {
        motor[port5] = 0;
    }

    datalogAddValue(1, SensorValue(magSens1));
    datalogAddValue(1, SensorValue(magSens2));

    if (SensorValue(magSens1) < READ_THRESH) {
     	motor[flagServoRight] = 127;
    } else {
    	motor[flagServoRight] = 0;
 	}

 	if (SensorValue(magSens2) < READ_THRESH) {
     	motor[flagServoLeft] = -127;
    } else {
    	motor[flagServoLeft] = 0;
    }

    /*if (c->btn7.down) {
    	motor[flagServoLeft] = 0;
    	motor[flagServoRight] = -127;
  	} else {
      motor[flagServoLeft] = 127;
      motor[flagServoRight] = 0;
    }*/
}
