#pragma config(Motor,  port2,           servo1,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           servo2,        tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//servo position values

int servo1Close = 0;
int servo1Middle = 0;
int servo1Far = 0;

int servo2Close = 0;
int servo2Middle = 0;
int servo2Far = 0;




//ir state
int irState = 1;











void set_lift ( int servo_port ) {
	if (vexRT[Btn6D] == 1) {
			motor[servo_port] = servo1Far; // Servo 1 Far position - Lift Down

		} else if (vexRT[Btn6U] == 1) {
			motor[servo_port] = servo1Close; // Servo 1 Close position - Lift Up

		} else {
			motor[servo_port] = servo1Middle; // Servo 1 Middle position - Lift Stop
		}

} // end lift function


void set_drive ( int servo_port ) {
	if (vexRT[Ch3] > 25) {
			motor[servo_port] = servo2Far; // Servo 2 Far position - Drive Forward

		} else if (vexRT[Ch3] < -25) {
			motor[servo_port] = servo2Close; // Servo 2 Close position - Drive Backwards

		} else {
			motor[servo_port] = servo2Middle; // Servo 2 Middle position - Drive Stop
		}

} // end drive function

void set_rotate ( int servo_port ) {
	if (vexRT[Ch1] > 25) {
			motor[servo_port] = servo2Far; // Servo 3 Far position - Rotate Right

		} else if (vexRT[Ch1] < -25) {
			motor[servo_port] = servo2Close; // Servo 3 Close position - Rotate Left

		} else {
			motor[servo_port] = servo2Middle; // Servo 3 Middle position - Rotate Stop
		}

} // end rotate function













task main()
{
	while (true) {






		//States
		switch (irState)
    {
    case 1: // Drive + Rotate


      if (vexRT[Btn6D] == 1 || vexRT[Btn6U] == 1) { // Lift Button Used

					irState = 2;                              // State = Rotate + Lift
      		for (int i=0; i<3; i++) {                 // Loop 3 Times
      				//sendChar(UART1, 0x33);                // IR Code: Rotate + Lift
      		}
      }

      set_drive(servo1);
      set_rotate(servo2);






      break;

    case 2: // Rotate + Lift


      if (abs(vexRT[Ch3]) > 25) { // Drive Button Used

					irState = 3;                              // State = Drive + Lift
      		for (int i=0; i<3; i++) {                 // Loop 3 Times
      				//sendChar(UART1, 0x33);                // IR Code: Drive + Lift
      		}
      }

      set_rotate(servo1);
      set_lift(servo2);





      break;

    case 3: // Drive + Lift



      if (abs(vexRT[Ch3]) > 25) { // Rotate Button Used

					irState = 1;                              // State = Drive + Lift
      		for (int i=0; i<3; i++) {                 // Loop 3 Times
      				//sendChar(UART1, 0x33);                // IR Code: Drive + Lift
      		}
      }

      set_drive(servo1);
      set_lift(servo2);





      break;

    default:
      //should not have to be used
    }




	} //while end



} //main end
