#pragma config(Motor,  port2,           servo1,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           servo2,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,           servo3,        tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//servo position values

int servo1Close = 0;
int servo1Middle = 0;
int servo1Far = 0;

int servo2Close = 0;
int servo2Middle = 0;
int servo2Far = 0;

int servo3Close = 0;
int servo3Middle = 0;
int servo3Far = 0;

task main()
{
	while true {


	}



}
